# Generated by Django 4.2.16 on 2024-12-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                ],
                default="scheduled",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team_one",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team_one",
                to="project.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="team_two",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team_two",
                to="project.team",
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matches_won",
                to="project.team",
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("player_one", "player_two"), name="unique_team"
            ),
        ),
    ]
