# Generated by Django 4.2.16 on 2024-12-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_match_status_alter_match_team_one_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="team_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team_two",
                to="project.team",
            ),
        ),
    ]
