# Generated by Django 4.2.16 on 2024-10-28 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mini_fb", "0002_test"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test",
        ),
    ]
